x=8
try:
  
  print(x)
except:
  print("An exception occurred")